### ISSUE TITLE
商榷一下 Chapter 12.3 代码显示结果

### ISSUE THREAD

**Issue by c2chance** [kingwjz/Node.js-code#2]
尝试执行了该代码片段， 显示结果与书中有出入， 或者由于 node.js 异步执行缘故造成？ 我这里显示的结果的顺序是： 201 - 203 - 401 - 202 - 402. 或者 401 - 201 - 202 - 402 - 203 或其他。 而你书中是顺序显示： 201 - 202 - 203 - 401 - 402.  我的环境是 Win7, Node.js v4.4.4

我实验了多次， 偶尔有如你书中的顺序结果， 大部分情况都不是尼。 按理单机调试， 就一个人在用， 机器并不繁忙， 如你的顺序结果才对。

**Comment by kingwjz** [comment]
Thanks for your issue~
My environment is Ubuntu 16.04, node old version(forget it), try and test~
I will test on win7 later...
keep on touch!
